#!/usr/bin/perl

#use warnings;
use strict;
print "\rRead list file:\tREADING";

open LIST, "<$ARGV[0]";

my @domains;

while ( <LIST> ) {
	chomp;
	$domains[$.-1] = $_;
}

close LIST;
print "\r               \t       ";
print "\rRead list file:\tDONE\n";

#print "@domains";
my $max = @domains;
my $i=0;
foreach my $domain ( @domains ) {
#	print $domain, "\t";
	my $site = "http://sci-hub.$domain";
	system("timeout 3 curl --connect-timeout 2 $site -o web/$domain 2>/dev/null");
	printf "\rCheck working domains:\t%d(%.2f%)", $i, $i/$max*100;
	$i++;
}
print "\rCheck working domains:\t$max(100%)\n";
